controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
    type: attribute

kernel:
    resource: App\Shared\Infrastructure\Kernel
    type: attribute